# Link the C runtime statically on MSVC so the binary runs on a clean machine
# without the Visual C++ redistributable (design §11).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
