# Runs the child twice against the same file and checks both lines are present in order.
file(REMOVE "${LOG}")
execute_process(COMMAND "${CHILD}" --utc T1 --rss-bytes 1 --log-file "${LOG}" RESULT_VARIABLE r1)
execute_process(COMMAND "${CHILD}" --utc T2 --rss-bytes 2 --log-file "${LOG}" RESULT_VARIABLE r2)
if(NOT r1 EQUAL 0 OR NOT r2 EQUAL 0)
  message(FATAL_ERROR "child exited with ${r1} / ${r2}")
endif()
file(STRINGS "${LOG}" lines)
list(LENGTH lines n)
if(NOT n EQUAL 2)
  message(FATAL_ERROR "expected 2 lines, got ${n}: ${lines}")
endif()
list(GET lines 0 first)
list(GET lines 1 second)
if(NOT first MATCHES "^T1 rss_bytes=1 elevated=(true|false)$")
  message(FATAL_ERROR "bad first line: ${first}")
endif()
if(NOT second MATCHES "^T2 rss_bytes=2 elevated=(true|false)$")
  message(FATAL_ERROR "bad second line: ${second}")
endif()
